use std::mem::transmute;
use capstone::ffi::*;
use capstone::ffi::detail::*;

impl ::cpu::core::CPU {
    pub unsafe fn execute_insn(&mut self, insn: &Insn) -> Option<u32> {
        match transmute(insn.id) {
            ARMInsn::ARM_INS_ADC   => self.exec_adc(insn),
            ARMInsn::ARM_INS_ADD   => self.exec_add(insn),
            ARMInsn::ARM_INS_AND   => self.exec_and(insn),
            ARMInsn::ARM_INS_B     => self.exec_b(insn),
            ARMInsn::ARM_INS_BFC   => self.exec_bfc(insn),
            ARMInsn::ARM_INS_BFI   => self.exec_bfi(insn),
            ARMInsn::ARM_INS_BIC   => self.exec_bic(insn),
            ARMInsn::ARM_INS_BL    => self.exec_bl(insn),
            ARMInsn::ARM_INS_BLX   => self.exec_blx(insn),
            ARMInsn::ARM_INS_BX    => self.exec_bx(insn),
            ARMInsn::ARM_INS_CLREX => self.do_nothing(insn),
            ARMInsn::ARM_INS_CLZ   => self.exec_clz(insn),
            ARMInsn::ARM_INS_CMP   => self.exec_cmp(insn),
            ARMInsn::ARM_INS_CMN   => self.exec_cmn(insn),
            ARMInsn::ARM_INS_CPS   => self.exec_cps(insn),
            ARMInsn::ARM_INS_DMB   => self.do_nothing(insn),
            ARMInsn::ARM_INS_DSB   => self.do_nothing(insn),
            ARMInsn::ARM_INS_EOR   => self.exec_eor(insn),
            ARMInsn::ARM_INS_ISB   => self.do_nothing(insn),
            ARMInsn::ARM_INS_LDM   => self.exec_ldm(insn),
            ARMInsn::ARM_INS_LDMDB => self.exec_ldmdb(insn),
            ARMInsn::ARM_INS_LDMIB => self.exec_ldmib(insn),
            ARMInsn::ARM_INS_LDR   => self.exec_ldr(insn),
            ARMInsn::ARM_INS_LDRB  => self.exec_ldrb(insn),
            ARMInsn::ARM_INS_LDRD  => self.exec_ldrd(insn),
            ARMInsn::ARM_INS_LDREX => self.exec_ldrex(insn),
            ARMInsn::ARM_INS_LDRH  => self.exec_ldrh(insn),
            ARMInsn::ARM_INS_LDRSB => self.exec_ldrsb(insn),
            ARMInsn::ARM_INS_LDRSH => self.exec_ldrsh(insn),
            ARMInsn::ARM_INS_MCR   => self.exec_mcr(insn),
            ARMInsn::ARM_INS_MLA   => self.exec_mla(insn),
            ARMInsn::ARM_INS_MLS   => self.exec_mls(insn),
            ARMInsn::ARM_INS_MOV   => self.exec_mov(insn),
            ARMInsn::ARM_INS_MOVW  => self.exec_mov(insn),
            ARMInsn::ARM_INS_MOVT  => self.exec_movt(insn),
            ARMInsn::ARM_INS_MRC   => self.exec_mrc(insn),
            ARMInsn::ARM_INS_MRS   => self.exec_mrs(insn),
            ARMInsn::ARM_INS_MSR   => self.exec_msr(insn),
            ARMInsn::ARM_INS_MVN   => self.exec_mvn(insn),
            ARMInsn::ARM_INS_MUL   => self.exec_mul(insn),
            ARMInsn::ARM_INS_ORR   => self.exec_orr(insn),
            ARMInsn::ARM_INS_PLD   => self.do_nothing(insn),
            ARMInsn::ARM_INS_POP   => self.exec_pop(insn),
            ARMInsn::ARM_INS_PUSH  => self.exec_push(insn),
            ARMInsn::ARM_INS_REV16 => self.exec_rev16(insn),
            ARMInsn::ARM_INS_RSB   => self.exec_rsb(insn),
            ARMInsn::ARM_INS_RSC   => self.exec_rsc(insn),
            ARMInsn::ARM_INS_SBC   => self.exec_sbc(insn),
            ARMInsn::ARM_INS_SBFX  => self.exec_sbfx(insn),
            ARMInsn::ARM_INS_SMLAL => self.exec_smlal(insn),
            ARMInsn::ARM_INS_SMULL => self.exec_smull(insn),
            ARMInsn::ARM_INS_STM   => self.exec_stm(insn),
            ARMInsn::ARM_INS_STMDB => self.exec_stmdb(insn),
            ARMInsn::ARM_INS_STMIB => self.exec_stmib(insn),
            ARMInsn::ARM_INS_STR   => self.exec_str(insn),
            ARMInsn::ARM_INS_STRB  => self.exec_strb(insn),
            ARMInsn::ARM_INS_STRBT => self.exec_strb(insn),
            ARMInsn::ARM_INS_STRD  => self.exec_strd(insn),
            ARMInsn::ARM_INS_STREX => self.exec_strex(insn),
            ARMInsn::ARM_INS_STRH  => self.exec_strh(insn),
            ARMInsn::ARM_INS_SXTH  => self.exec_sxth(insn),
            ARMInsn::ARM_INS_SUB   => self.exec_sub(insn),
            ARMInsn::ARM_INS_SVC   => self.exec_svc(insn),
            ARMInsn::ARM_INS_TEQ   => self.exec_teq(insn),
            ARMInsn::ARM_INS_TST   => self.exec_tst(insn),
            ARMInsn::ARM_INS_UBFX  => self.exec_ubfx(insn),
            ARMInsn::ARM_INS_UMLAL => self.exec_umlal(insn),
            ARMInsn::ARM_INS_UMULL => self.exec_umull(insn),
            ARMInsn::ARM_INS_UXTAB => self.exec_uxtab(insn),
            ARMInsn::ARM_INS_UXTAH => self.exec_uxtah(insn),
            ARMInsn::ARM_INS_UXTB  => self.exec_uxtb(insn),
            ARMInsn::ARM_INS_UXTH  => self.exec_uxth(insn),
            ARMInsn::ARM_INS_WFI   => self.do_nothing(insn),
            _ => {
                self.dump_state();
                ::util::dump_insn(insn, true);
                unreachable!()
            }
        }
    }
}
